#!/bin/bash
if [ ! -f ".env" ]; then
  echo ".env file not found in project root: Creating new!"
  echo "PROJECT_PATH=$(pwd)" >> .env
  echo "ELIXIR_PATH=$(which elixir)" >> .env
  echo "TYPE_CHECK_DEBUG_ENABLED=false" >> .env
fi
if [ ! -d "venv" ]; then
  echo "Virtual environment not installed: Installing first!"
  curl -o get-pip.py https://bootstrap.pypa.io/get-pip.py
  python3 get-pip.py
  rm get-pip.py
  python3 -m pip install virtualenv
  python3 -m venv venv
  source venv/bin/activate
  python3 -m pip install -r requirements.txt
fi
export PYTHONPATH="${PWD}/src:${PYTHONPATH}"
source venv/bin/activate
python3 src/gradualelixir/cli.py "$@"
