
[tool.black]
line-length = 120
include = "src/gradualelixir"

[tool.mypy]
files = "src/gradualelixir/"
disallow_any_unimported = true
ignore_missing_imports = true

[tool.isort]
known_third_party = "gradualelixir"
profile="black"
